### ISSUE TITLE
关于论文的一些问题

### ISSUE THREAD

**Issue by yanghh2000** [Jacob-Zhou/simple-csc#1]
作者你好，关于论文我有几个问题，希望您帮我解答一下：
1. 我理解论文提出的方法其本质似乎也是一种candidates（identical，拼音/字形）召回+score排序 的方法，只不过这里scoring model换成了LLM？
2. Distortion Model的各种type priority是怎么确定的。
3. 章节2.5 Faithfulness Reward里“苏州”和“宿州”的例子和entropy的关系是什么呢，我理解这个例子可以通过增加indentical priority来解决，但为什么却是加一个entropy score来做我不太能理解这个点。

**Comment by Jacob-Zhou** [comment]
Hello，感谢您对我们工作的关注！下面是针对您问题的一些解答：

1. **我们论文的方法和"召回+排序"方法的关系**：我们论文的方法的确和"candidates（identical，拼音/字形）召回+score排序"方法(下面简称为"召回+排序")有着特别密切的联系。但是我们的方法并不是"召回+排序"方法的一种特例，而是我们的方法和"召回+排序"其实都是噪音信道模型， $p(\boldsymbol{y}|\boldsymbol{x})=\frac{p(\boldsymbol{y})p(\boldsymbol{x}|\boldsymbol{y})}{p(\boldsymbol{x})}$ ，的不同的近似实现方式。在 "召回+排序" 方法中 $p(\boldsymbol{x}|\boldsymbol{y})$ 被定义为了一个离散函数，如果 $\boldsymbol{y}$ 是一条根据 identical、拼音、字形召回的句子的话，那么值为 1 否则值为 0。而我们通过 Distortion Model 的方式建模了一个连续的 $p(\boldsymbol{x}|\boldsymbol{y})$。同时，我们的方法还能实现一些"召回+排序"做不到的事情。如附录 B.4 提到的，我们在实现的时候并不会完全放弃 unrelated 的 token。对于这些 token，我们会给一个较小的概率值。这让我们的方法实际上可以改对许多“没有召回”的字音字形无关的错误。
2. **关于 type priority 的问题**： 首先，这儿可能有个关于 "type priority" 的误解。在论文中我们的 "type priority" 指的实际上是，如果一个 pair 可以被归类到多个类型，那么我们优先选择 priority 靠前的那个类型。例如，"机" 和 "肌" 可以被归类到拼音相近也可以被归类到字形相近，但是根据 "type priority"，我们将其归类为字形相近。而这个 "type priority" 主要是根据前人工作 (如 CSCD-NS) 中提到的，同音错误出现的频率要大于近音错误出现的频率大于形近错误出现的频率，而启发地确定的。另外根据问题 3，你可能想知道的是 "type probability" 是怎么确定的。在 2.1 小节中我们有提及，我们是直接在 3.1 小节中提到的 Pseudo development set 中的 2,000 句数据集中统计得到的。
3. **关于 entropy score 的问题**： 的确，这种情况可以通过人为的加大其他类型和 identical 类型之间的概率差异 (gap) 来缓解。但是这种方法会额外引入一个新的全局固定的超参。我们希望找到个动态的方法来对这个 gap 进行自适应的调整。在合适的时候，例如在句子开头以及预测地名、人名的时候，这个 gap 会自动变大以保留原文，而在模型比较确定下一个 token 需要选什么的时候，就减少干预。这个时候 entropy score 就是一个比较理想的选择。

**Comment by yanghh2000** [comment]
感谢作者详细且清晰的回答，解决我很多疑惑。关于第3点我还想继续问一下，你提到：
“在合适的时候，例如在句子开头以及预测地名、人名的时候，这个 gap 会自动变大以保留原文，而在模型比较确定下一个 token 需要选什么的时候，就减少干预。这个时候 entropy score 就是一个比较理想的选择。”
这里在预测地名和人名的时候，为什么概率分布会变得不确定，正如你举的“苏州”和“宿州”的例子，苏州的概率是远远大于宿州，按道理来说entropy应该不会特别大？那么LLM应该比较会比较确定地选择“苏州”才对把

**Comment by Jacob-Zhou** [comment]
1. **为什么在预测地名和人名的时候概率会变得不确定**：是这样的，“小明想去” 这个片段因为没有足够多的上下文作为支撑，因此后面可以接的 token 特别多，比如所有的动作“看”、“听”、“写代码”或者地名“博物馆”、“实验室”或者“苏州”和“宿州”。这些词语放在这儿都是合理的，因此 LLM 的 entropy 会较大。同理在预测人名的时候，如果上下文没有提供足够多的信息，那么模型将分配一个较为扁平的概率给所有的姓以及名字常用字。比如说“这家上市集团的总经理叫做”后面可以接百家姓中的任意一个，因此 entropy 也会比较大。而如果是“阿里巴巴的创始人叫做”后面很大概率会接“马”，这时候 entropy 就会比较小，但很多时候我们遇到的是前一种情况。
2. **为什么在概率相差那么大的情况下，熵依旧起了作用**：下图是在 Baichuan2 14B Base 上的 token 概率分布。可以看到 “小明想去” 后接 “苏州” 的对数概率是 -7.12，而接 “宿州” 的对数概率是 -12.48。相差了 -5.36，这个大于 Same Pinyin 的 -3.75 的惩罚，但是熵为 6.429 归一化后为 0.5475，在乘上熵得分后这里 Same Pinyin 的惩罚将会变为 5.80，这样一来就避免了选择 “苏州”。论文中给出的例子可能是小一点的模型的概率分布 (有点忘记当初是用哪个模型得到的了)，因此是有可能没法避免选择 “苏州” 的。实际上我们在做 Demo 的时候也发现 Qwen1.5 0.5B 的模型还是容易过纠这个 case 的 :(。

![CF82FC62-CAB1-43D5-B78B-C0684225EC41](https://github.com/user-attachments/assets/460a1222-06ab-4cc2-8db8-8e3e48845daa)

**Comment by Jacob-Zhou** [comment]
这个是小说数据集中的一个例子，可以比较容易看到模型预测的熵是怎么变化的。基本上就是如果通过上下文可以比较确定地进行推断的地方就会有个较小的熵，而模型不确定的地方就会有更大的熵。

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/eca9b183-36b3-4563-9c99-776c99bd195a">

**Comment by yanghh2000** [comment]
明白了，非常感谢您耐心的解答！我看到你们拿了金山文本校对大赛第一名，是把这个方法迁移到语法纠错上吗？后续考虑公开相关技术方案吗

**Comment by Jacob-Zhou** [comment]
是的！不过我们在这个基础上做了俩事情。一个是我们修改了Distortion Model，加入添字、少字和乱序这三个 token 级别的错误类型，此外还加入了一个拼音首字母相同的错误类型 (机器->军区)。然后我们为了找到更好的 type probability 在主办方提供的高质量训练集上进行了 grid search。后续我们也会开源这些修改。Top-k voting (进行beam size 为 k 的解码后，将得到的这 k 个结果进行投屏集成) 对单模型结果有提升，但是最终集成的时候提升不大。

**Comment by yanghh2000** [comment]
我比较好奇这种不微调能比得过传统的Bert和BART微调吗？

**Comment by Jacob-Zhou** [comment]
看情况，如果训练集和测试集相似度很高的话，比如 sighan 这种 97% 的编辑对都在训练集中见过了，bert 和 bart 微调更有优势 (过拟合了)。而训练集中没见过的那些编辑对上，我们这种方法做得更好。

**Comment by Jacob-Zhou** [comment]
从前人论文来看 bart 改句法不错，但是在拼写纠错任务上表现不好。具体为啥没细究。

<img width="769" alt="image" src="https://github.com/user-attachments/assets/a2068fd8-92b9-4263-8854-746a79727697">

**Comment by yanghh2000** [comment]
好的好的，十分感谢解答！

**Comment by yanghh2000** [comment]
我还有个问题：为什么不让LLM能看见input text然后再纠错呢？

**Comment by Jacob-Zhou** [comment]
其实试过，性能会掉。主要是发现一旦大模型看到了input，那么他有些地方就会不改了，直接复制复制原文，导致掉r。

**Comment by yanghh2000** [comment]
确实，我试了一下也是，不过现实场景中是可以先微调一下llm适应这个任务之后再用吧。

**Comment by Jacob-Zhou** [comment]
pycorrector 的作者前段时间发布过一个微调过的模型，shibing624/chinese-text-correction-7b。不知道用进来效果咋样。之前打金山比赛的时候试过用他们的代码直接跑，效果一般般。

**Comment by ketour** [comment]
> 是的！不过我们在这个基础上做了俩事情。一个是我们修改了Distortion Model，加入添字、少字和乱序这三个 token 级别的错误类型，此外还加入了一个拼音首字母相同的错误类型 (机器->军区)。然后我们为了找到更好的 type probability 在主办方提供的高质量训练集上进行了 grid search。后续我们也会开源这些修改。Top-k voting (进行beam size 为 k 的解码后，将得到的这 k 个结果进行投屏集成) 对单模型结果有提升，但是最终集成的时候提升不大。

点赞！请问有开源这部分代码的打算和计划么？想学习一下 : )

**Comment by Jacob-Zhou** [comment]
> > 是的！不过我们在这个基础上做了俩事情。一个是我们修改了Distortion Model，加入添字、少字和乱序这三个 token 级别的错误类型，此外还加入了一个拼音首字母相同的错误类型 (机器->军区)。然后我们为了找到更好的 type probability 在主办方提供的高质量训练集上进行了 grid search。后续我们也会开源这些修改。Top-k voting (进行beam size 为 k 的解码后，将得到的这 k 个结果进行投屏集成) 对单模型结果有提升，但是最终集成的时候提升不大。
> 
> 点赞！请问有开源这部分代码的打算和计划么？想学习一下 : )

有开源的计划的。但可能还需要再过段时间。
